### ISSUE TITLE
Please consider moving it under Processing

### ISSUE THREAD

**Issue by pcav** [jagodki/Closest-Points#1]
so it will be easier to maintaining, and much more powerful (running in batch mode, recursive, modeller, etc.)
Thanks

**Comment by jagodki** [comment]
Hello Paolo,

it already supports the processing frame work, see [processing_provider.py](https://github.com/jagodki/Closest-Points/blob/master/src/closest_points/processing_provider.py).
I updated the readme to figure out, that the plugin is also available via toolbox and processing framework.

Sincerely,
Christoph

**Comment by pcav** [comment]
Tanks for the clarification.
