### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by srothe-oslo** [jagodki/Closest-Points#2]
Hello,
I may have come across a bug in your plugin: You state to use the Feature ID of source and target features in your fields "from_fid" and "to_fid". However, it seems to me that you actually use the ROWID of the source layer. I have used the plugin with a point layer of targets, and calculated the distance to another points layer. Before doing so, I had removed a few features in the (source) point layer. Now, the values in the field "from_fid" of your generated layer point to the rowIDs of the original layer, not their fid's. Since the ROWID is just a consecutive number, while the Feature ID (fid) does not change after assignment, the plugin does not match any features with fid > than highest ROWID, and when looking up a feature based of the fid your plugin returns, wrong features are retrieved.

**Comment by jagodki** [comment]
Hi,

yes, this could be a problem. I will make some tests and have a look into the code during the next days, to isolate the problem. I will write you, when I have some results.

Sincerely,
Christoph

**Comment by jagodki** [comment]
I detected the problem:

In the result layer, the fields “from_id” and “to_id” do not contain the fids (getting from QgsFeature.id()), but the index when I iterate over all features of the layers using layer.getFeatures(). I will remove this bug as fast as possible.

**Comment by jagodki** [comment]
I recently uploaded a new version of the plugin. The bug should not be existing anymore.

**Comment by srothe-oslo** [comment]
Nice! I'll check it out this week. Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Christoph <notifications@github.com>Datum: Di., 14. Juli 2020, 20:46An: jagodki/Closest-Points <Closest-Points@noreply.github.com>Cc: srothe-oslo <stefan@hess-rothe.net>, Author <author@noreply.github.com>Betreff: Re: [jagodki/Closest-Points] Possible bug (#2)
I recently uploaded a new version of the plugin. The bug should not be existing anymore.
